apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: ilhamellya/todo:v1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: todo-env